{% set name = "lastversion" %}
{% set version = "1.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lastversion-{{ version }}.tar.gz
  sha256: 8be68e865cfb70c8089ea9cb25803e0d8fe60435cc663b9e014858885b946214

build:
  number: 0
  entry_points:
    - lastversion = lastversion:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - appdirs
    - beautifulsoup4
    - cachecontrol
    - distro
    - feedparser
    - lockfile
    - packaging
    - python
    - python-dateutil
    - pyyaml
    - requests >=2.6.1
    - six
    - tqdm

test:
  imports:
    - lastversion
  commands:
    - pip check
    - lastversion --help
  requires:
    - pip

about:
  home: https://github.com/dvershinin/lastversion
  summary: A CLI tool to find the latest stable version of an arbitrary project
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aquohn
