{% set name = "libdecsync" %}
{% set version = "2.1.0.post1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/libdecsync-{{ version }}.tar.gz
  sha256: cc0a07dd7fb0032331646f6724821aef7dd69ae40a207a052026943e54c24193

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - libdecsync
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/39aldo39/libdecsync-bindings-python3
  summary: Python3 bindings for libdecsync
  license: LGPL-2.1-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - aquohn
