{% set name = "radicale-storage-decsync" %}
{% set version = "1.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/radicale_storage_decsync-{{ version }}.tar.gz
  sha256: 70b552246ac50ef7f1ef07de091c53096800e9cbf128ab19673215c6a28e45d7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - libdecsync >=1.3.1
    - python
    - radicale >=3

test:
  imports:
    - radicale_storage_decsync
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/39aldo39/Radicale-DecSync
  summary: DecSync storage plugin for Radicale
  license: GPL-3.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - aquohn
