{% set name = "radicale-storage-decsync" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-','_') }}-{{ version }}.tar.gz
  sha256: e4c513bd3b68d5eae07009c7881ec9f1af76b9b37e19b056c2e29414945ea63b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - libdecsync >=2.0.0
    - python
    - radicale >=3

test:
  imports:
    - radicale_storage_decsync
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/39aldo39/Radicale-DecSync
  summary: DecSync storage plugin for Radicale
  license: GPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - aquohn
