{% set name = "radicale" %}
{% set version = "3.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Radicale-{{ version }}.tar.gz
  sha256: a9433d3df97135d9c02cec8dde4199444daf1b73ad161ded398d67b8e629fdc6

build:
  number: 0
  noarch: python
  entry_points:
    - radicale = radicale.__main__:run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - defusedxml
    - passlib
    - python >=3.5
    - python-dateutil >=2.7.3
    - vobject >=0.9.6

test:
  imports:
    - radicale
    - radicale.app
  commands:
    - pip check
    - radicale --help
  requires:
    - pip

about:
  home: https://radicale.org/
  summary: CalDAV and CardDAV Server
  license: GPL-3.0
  license_file: COPYING

extra:
  recipe-maintainers:
    - aquohn
